### ISSUE TITLE
Use Door, Switch (with more than 1 value)

### ISSUE THREAD

**Issue by arnauddorgans** [etwmc/Personal-HomeKit-HAP-#23]
hey :) 
i use lights and switch with this code : http://pastebin.com/rMdVzW3J
but i fail to understand how use door/garage door or switch with 5 values for exemple
any idea ? :)
thx

**Comment by rooi** [comment]
Hi,

I would like to add a speaker and use the output volume as specified as enum. Unfortunately I cannot get it to work. Any ideas why?

**Comment by etwmc** [comment]
Have you try set the service type to fan
It doesn't make sense, but it's the only service type without predefine attributes. (You need to set it up as a set. thermostat has five attributes, light have two)
And because Apple doesn't actually publicly declare HomeKit has such function, we don't know what's attribute constitute a speaker. 
But my guess, speaker would mean remote speaker, so you also need attribute of codec. (Those start with RTCP) 
But if you want to control the volume only, using fan as attribute is the only way right now.

**Comment by rooi** [comment]
Thanks! I'll try you suggestions
