### ISSUE TITLE
just a query

### ISSUE THREAD

**Issue by mayurcools** [etwmc/Personal-HomeKit-HAP-#31]
Is it possible to put avahi source here in project just like srp and chacha libraries?
so that when we run PHK, bonjour service will get set up and the dependency on having avahi daemon is removed? also can we use mDNSresponder source from apple?

Thank you.

**Comment by etwmc** [comment]
The problem is this project was designed for implement in MCU, which avahi is not available and we have to use some mDNS implementation, and in ble is useless. 
But srp and chacha not only needed full time, I also need to change the message digest to sha512, and link to function definition in the Configuration.h to made the library behavior as the HomeKit protocol intended. But I only use the function exposed by the avahi API (actually I developed on OS X and port it to Linux as a middle part)
Consider avahi package used is a apt-get command away from download in Ubuntu, and it's not the critical component. (I imagine you could use any implementation of Bonjour protocol you like, given the function name is a public knowledge. ) I don't think I will include the source any day soon. 

Wai Man Chan
